### ISSUE TITLE
Ubicación RA

### ISSUE THREAD

**Issue by Luftwaffe-boy** [SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-equipo-irving-1#1]
[RA_UbicacionGPS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-8-reconocimeinto-gps-equipo-irving-1/files/15168389/RA_UbicacionGPS.pdf)

**Comment by JudithReynaCS** [comment]
EXCELENTE :) 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
